### ISSUE TITLE
Document snippets in search results

### ISSUE THREAD

**Issue by ghost** [PeARSearch/PeARS#13]
Regarding the issues discussed in the Copyright vs Privacy blog post [http://aurelieherbelot.net/copyright-vs-privacy/], would storing and using the contents of the meta description tag count as fair use and be permissible?

Another possibility would be using the Open Directory Project description, although I'm not sure of the ODP's current status and future prospects.

I appreciate that in some cases you would ideally display the snippet of the page that contains the search keywords, but anecdotally, my experience using commercial search engines suggests that they opt for this over the page description less than might be expected. In cases where they do, it can actually result in unusual and user-unfriendly behaviour by the page owner who (kind of understandably) wants to prevent key information from appearing in the description to ensure the user visits their site.

Displaying a fixed page description and combining it with data on how the result has been matched such as your word cloud might be a reasonable compromise for all?

**Comment by minimalparts** [comment]
Thanks for the thoughts! Yes, your point about commercial search engine behaviour is a good one. Personally, I think I tend to orient myself through the title of the page. My reliance on matching keywords in the snippet only comes into account when I try to find the answer to my question directly in the search results, without having to click on a link (this usually happens when I have simple programming questions).

So your suggestion to have a fixed page description plus the word cloud is nice. I have been toying with the idea of providing an automatic summariser with the indexing part of PeARS, so that (non-copyrighted) page descriptions are produced on the fly. Not that summarisers are particularly good right now, but they will be in the future, and it might be a nice comprise.

**Comment by ghost** [comment]
Thanks for the response. One other thought regarding the legalities - how are copyright considerations applied to public proxy servers? It's obviously not quite the same but the content is still being stored and redistributed. Is there any precedent in this area that would justify storing the raw document in your index?

I think the project is a really interesting idea and wish you all the best of luck with it.

**Comment by minimalparts** [comment]
The current fix is to check whether the page is under CC license (as best as we can) and provide a snippet if it is. A page summary would still be nice to have. But let's have this as future work!
